# Next step is to split the 111 champions in classes

# One possible class split is presented on a fan supported website
# and describes three types of heros:

strength = [
    'Abaddon',
    'Alchemist',
    'Axe',
    'Beastmaster',
    'Brewmaster',
    'Bristleback',
    'Centaur Warrunner',
    'Chaos Knight',
    'Clockwerk',
    'Doom',
    'Dragon Knight',
    'Earth Spirit',
    'Earthshaker',
    'Elder Titan',
    'Huskar',
    'Io',
    'Kunkka',
    'Legion Commander',
    'Lifestealer',
    'Lycan',
    'Magnus',
    'Night Stalker',
    'Omniknight',
    'Phoenix',
    'Pudge',
    'Sand King',
    'Slardar',
    'Spirit Breaker',
    'Sven',
    'Tidehunter',
    'Timbersaw',
    'Tiny',
    'Treant Protector',
    'Tusk',
    'Underlord',
    'Undying',
    'Wraith King',
]

agility = [
    'Anti-Mage',
    'Arc Warden',
    'Bloodseeker',
    'Bounty Hunter',
    'Broodmother',
    'Clinkz',
    'Drow Ranger',
    'Ember Spirit',
    'Faceless Void',
    'Gyrocopter',
    'Juggernaut',
    'Lone Druid',
    'Luna',
    'Medusa',
    'Meepo',
    'Mirana',
    'Monkey King',
    'Morphling',
    'Naga Siren',
    'Nyx Assassin',
    'Pangolier',
    'Phantom Assassin',
    'Phantom Lancer',
    'Razor',
    'Riki',
    'Shadow Fiend',
    'Slark',
    'Sniper',
    'Spectre',
    'Templar Assassin',
    'Terrorblade',
    'Troll Warlord',
    'Ursa',
    'Vengeful Spirit',
    'Venomancer',
    'Viper',
    'Weaver',
]

intelligence = [
    "Ancient Apparition",
    "Bane",
    "Batrider",
    "Chen",
    "Crystal Maiden",
    "Dark Seer",
    "Dark Willow",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Enchantress",
    "Enigma",
    "Invoker",
    "Jakiro",
    "Keeper of the Light",
    "Leshrac",
    "Lich",
    "Lina",
    "Lion",
    "Nature's Prophet",
    "Necrophos",
    "Ogre Magi",
    "Oracle",
    "Outworld Devourer",
    "Puck",
    "Pugna",
    "Queen of Pain",
    "Rubick",
    "Shadow Demon",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Storm Spirit",
    "Techies",
    "Tinker",
    "Visage",
    "Warlock",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Zeus",
]


def get_class(hero_name):
    if hero_name in agility:
        return 'agility'
    elif hero_name in intelligence:
        return 'intelligence'
    elif hero_name in strength:
        return 'strength'
    else:
        return 'none'
